[main]
mode="demo" #运行的模式：dev,demo,prod，线上环境请一定配置prod
log_level="trace" #全局的日志输出等级:panic,fatal,error,warn,info,debug,trace
# log_path="./logs/" #日志文件保存位置 默认不保存到文件
time_zone="Asia/Shanghai"
secret_key = "2c320e24aa9d40b9"
static_server_name=""

[redis]
host="db_host:6379"
password=""
db=0
prefix=""

[database]
driver="mysql"
dsn = "root:root@tcp(db_host:3306)/haotrader?charset=utf8&loc=Local"
show_sql = true
prefix="tt_"


[local] 
symbols=[]


[haoadm]
readonly=false
site_name="HaoTrader 运营管理系统"
listen="0.0.0.0:8079"



[haomatch]
cache="haomatch.db"
listen="0.0.0.0:8083"



[haoquote]
listen="0.0.0.0:8081"
# 支持的周期 "m1", "m3", "m5", "m15", "m30", "h1", "h2", "h4", "h6", "h8", "h12", "d1", "d3", "w1", "mn"
period=["m1", "d1"]


[haobase]
listen="0.0.0.0:8082"
internal_api_allow_ip=["127.0.0.1"]










