[main]
mode="demo" #运行的模式：dev,demo,prod，线上环境请一定配置prod
log_level="trace" #全局的日志输出等级:panic,fatal,error,warn,info,debug,trace
# log_path="./logs/" #日志文件保存位置 默认不保存到文件
time_zone="Asia/Shanghai"


[redis]
host="127.0.0.1:6379"
password=""
db=0
prefix=""

[database] # 支持mysql, sqlite3, postgres
driver="mysql"
dsn = "root:root@tcp(localhost:3306)/haotrader?charset=utf8&loc=Local"

# driver="sqlite3"
# dsn = "./test.sqlite.db"

# driver = "postgres" 
# dsn = "host=localhost port=15432 user=postgres password=postgres dbname=haotrader sslmode=disable"


show_sql = true


[local] 
symbols=[]


[haoadm]
site_name="HaoTrader 运营管理系统"
listen="0.0.0.0:8079"
server_name=""
static_server_name=""


[haomatch]
cache="haomatch.db"



[haoquote]
listen="0.0.0.0:8081"
cache="haoquote.db"
# 支持的周期 "m1", "m3", "m5", "m15", "m30", "h1", "h2", "h4", "h6", "h8", "h12", "d1", "d3", "w1", "mn"
period=["m1", "d1"]


[haobase]
listen="0.0.0.0:8082"










